import type { FastifyInstance } from "fastify";
import { currentSession } from "../session-guard.js";
import { RegisterPage, type RegisterRow } from "../views/register.js";

const mockRegisterData: ReadonlyArray<RegisterRow> = [
  {
    reportId: "r1",
    sn: 1,
    tmda_report_number: "AEMD/2026-27/001",
    date_received: "2026-06-07",
    device_brand_name: "Revital Infusion giving set",
    device_common_name: "Infusion giving set",
    size: "NOT STATED",
    batch_lot_serial_number: "2601304-02",
    device_type: "MD",
    manufacturing_date: "2026-01-01",
    expiry_date: "2030-12-01",
    manufacturer_name_address: "Revital Healthcare (EPZ) Ltd, Takaungu 80100 Mombasa",
    manufacturing_country: "Kenya",
    supplier_name: "MSD/GOT",
    event_description: "Blockage",
    date_onset_event: "2026-05-10",
    date_report: "2026-05-10",
    event_location: "BIMA pharmacy",
    region: "Dodoma",
    type_of_report: "Initial",
    reporter_details: "Grace Katunzi, P.O.BOX DODOMA RH, 0717788929",
    event_seriousness: "NO",
    causality_assessment: "Probable",
    risk_assessment: "High",
    regulatory_action: "CONDUCT FIELD INVESTIGATION",
    assessor_1_name: "SUZANA T RUHOGORA",
    date_assessment_1: "21/7/2026",
    assessor_2_name: "",
    date_assessment_2: "",
    acknowledgement_feedback: "",
  },
  {
    reportId: "r2",
    sn: 2,
    tmda_report_number: "AEMD/2026-27/002",
    date_received: "2026-06-07",
    device_brand_name: "Surgimed Medical Supplies Ltd",
    device_common_name: "Insulin Syringe with needle",
    size: "1 ml",
    batch_lot_serial_number: "23973711.0",
    device_type: "MD",
    manufacturing_date: "2023-09-01",
    expiry_date: "2026-08-28",
    manufacturer_name_address: "Surgimed Medical Supplies Ltd",
    manufacturing_country: "Tanzania",
    supplier_name: "MSD/GOT",
    event_description: "Blockage",
    date_onset_event: "2026-06-29",
    date_report: "2026-06-30",
    event_location: "DRRH 9094",
    region: "Dodoma",
    type_of_report: "Initial",
    reporter_details: "Abel Karavuze, DRRH 904 DODOMA, 0767054810",
    event_seriousness: "NO",
    causality_assessment: "Possible",
    risk_assessment: "Medium",
    regulatory_action: "CONDUCT FIELD INVESTIGATION AND ENHANCE MONITORING",
    assessor_1_name: "SUZANA T RUHOGORA",
    date_assessment_1: "23/7/2026",
    assessor_2_name: "",
    date_assessment_2: "",
    acknowledgement_feedback: "",
  },
  {
    reportId: "r3",
    sn: 3,
    tmda_report_number: "AEMD/2026-27/003",
    date_received: "2026-06-07",
    device_brand_name: "i syringe",
    device_common_name: "sterile syringe",
    size: "10 ml",
    batch_lot_serial_number: "251104.0",
    device_type: "MD",
    manufacturing_date: "2025-11-01",
    expiry_date: "2030-10-01",
    manufacturer_name_address: "Medical Dawila Ltd. Plot P14562, Kigogo Kisarawe II, Kigamboni, Dar es Salaam",
    manufacturing_country: "Tanzania",
    supplier_name: "MSD/GOT",
    event_description: "Blockage 1ml insulin syringe",
    date_onset_event: "30/6/2026",
    date_report: "2026-06-30",
    event_location: "EMD",
    region: "Dodoma",
    type_of_report: "Initial",
    reporter_details: "Edina Mlindasungu, DRRH DODOMA, 0755359935",
    event_seriousness: "NO",
    causality_assessment: "Possible",
    risk_assessment: "Medium",
    regulatory_action: "CONDUCT FIELD INVESTIGATION AND ENHANCE MONITORING",
    assessor_1_name: "SUZANA T RUHOGORA",
    date_assessment_1: "23/7/2026",
    assessor_2_name: "",
    date_assessment_2: "",
    acknowledgement_feedback: "",
  },
  {
    reportId: "r4",
    sn: 4,
    tmda_report_number: "AEMD/2026-27/004",
    date_received: "2026-06-07",
    device_brand_name: "Surgical face mask",
    device_common_name: "Face mask",
    size: "",
    batch_lot_serial_number: "260216.0",
    device_type: "MD",
    manufacturing_date: "2026-02-01",
    expiry_date: "2028-01-01",
    manufacturer_name_address: "MSD P.O.BOX 9081 DAR ES SALAAM",
    manufacturing_country: "Tanzania",
    supplier_name: "MSD",
    event_description: "Facemask without straps and some with broken straps",
    date_onset_event: "2026-06-15",
    date_report: "2026-06-15",
    event_location: "DRRH 904",
    region: "Dodoma",
    type_of_report: "Initial",
    reporter_details: "Abel Karavuze, DRRH 904 DODOMA, 0767054810",
    event_seriousness: "NO",
    causality_assessment: "Certain",
    risk_assessment: "Critical",
    regulatory_action: "Request for labelling and design changes and Request Post marketing Studies",
    assessor_1_name: "Suzana T Ruhogora",
    date_assessment_1: "24/7/2026",
    assessor_2_name: "",
    date_assessment_2: "",
    acknowledgement_feedback: "",
  },
  {
    reportId: "r5",
    sn: 5,
    tmda_report_number: "AEMD/2026-27/005",
    date_received: "2026-06-07",
    device_brand_name: "HEUER",
    device_common_name: "Infusion giving set",
    size: "",
    batch_lot_serial_number: "",
    device_type: "MD",
    manufacturing_date: "2026-06-01",
    expiry_date: "2030-12-01",
    manufacturer_name_address: "Encore Medics Ltd P.O.BOX 10186, Dar es Salaam",
    manufacturing_country: "Tanzania",
    supplier_name: "MSD",
    event_description: "Blockage",
    date_onset_event: "",
    date_report: "2026-06-16",
    event_location: "BIMA pharmacy",
    region: "Dodoma",
    type_of_report: "Initial",
    reporter_details: "Grace Katunzi, P.O.BOX DODOMA RH, 0717788929",
    event_seriousness: "NO",
    causality_assessment: "Probable",
    risk_assessment: "High",
    regulatory_action: "Conduct field investigation",
    assessor_1_name: "Suzana T Ruhogora",
    date_assessment_1: "24/7/2026",
    assessor_2_name: "",
    date_assessment_2: "",
    acknowledgement_feedback: "",
  },
];

export async function registerRoutes(app: FastifyInstance): Promise<void> {
  app.get("/register", async (request, reply) => {
    const session = currentSession(request);

    return reply.html(
      <RegisterPage
        rows={mockRegisterData}
        viewerRole={session.role}
        viewerName={session.fullName}
      />
    );
  });
}
